# Generated by Django 4.1.7 on 2023-03-17 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_project_expense', '0004_alter_expense_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
